### ISSUE TITLE
What info do you need in the `wps_links.yml` file?

### ISSUE THREAD

**Issue by agstephens** [cedadev/ceda-wps-assets#1]
@gap736uk : I have put together a draft YAML file for the you to query so that you can populate links in MOLES records:

https://github.com/cedadev/ceda-wps-assets/blob/main/ceda_wps_assets/assets/wps_links.yml

Does it have all the information you would require? I assume you need:

- MOLES URL
- URL of WPS UI submission form
- Text for the URL to the WPS UI

Is there anything else that would be useful? Or that you would want to connect/push the other way from MOLES?

**Comment by gap736uk** [comment]
I'm wondering if we're missing something here  - is there a connection that we're missing that allows us to determine what the mapping is between MOLES and the WPS?

e.g. a WPS will have some functionality and criteria associated with it I would imagine in terms of it archive scope... e..g point in the archive to which it relates, file format, etc. 

If these could be codified such that it would be possible to then look them up somehow... and visa versa back the other way... 

MOLES has an API end point that gives the ability to look up a record for a given path. That path may be at or below a given Observation's Result Path.

Is there a similar index for the WPS end-points, or is this what is being constructed here. If it is, then could it be constructed in such a way that MOLES info isn't needed to be stored here per se, but the WPS index allows:

1) identification of associated archive paths for a given WPS operation
2) has an API to allow checking against a given path for associated WPS functionality and links?
3) gives the ability for the WPS to use the associated paths to then do a look-up using the MOLES path_to_record API endpoint to get the relevant links to MOLES records?

**Comment by gap736uk** [comment]
Given the above may not be possible (all depends on the WPS conceptual model, but I suspect that can't be that well defined), then returning to this issue, the following would be needed for a WPS tool entry to allow MOLES linkage:

1) Title of function to appear in Online Resource entry in MOLES
2) URL to tool
3) Function type (incase this differs from Data Tool)
4) Associated MOLES Observation UUIDS/URLS

Additionally, to go back the other way (i.e. for the WPS to then be able to provide the necessary MOLES details) the WPS would require one of two approaches here:


Option 1:
a) pull back the MOLES uuid/URL 
b) poll API to get details for each MOLES entry (title, access type*)

Option 2:
a) pull back MOLES uuid/URL
b) get stored MOLES details for title, access type, access link (if necessary)

**Comment by agstephens** [comment]
@gap736uk thanks for your thoughts. I think the _first_ step required is to be able to say that we have two separate entities that are linked:

1. A MOLES entry (via its URL)
2. A WPS Process (via its URL)

The current setup means that this can be a one-to-one, many-to-one, one-to-many, or many-to-many relationship. So I don't think it'll be simple. I think the first step is to have a place where we control/manage the connections (in a YAML files). In future, we can make it more dynamic. But initially, we can create scripts to dump out the required YAML and be done with it.

So, let's stick with:

1. Title of function to appear in Online Resource entry in MOLES
2. URL to tool
3. Function type (incase this differs from Data Tool)
4. Associated MOLES Observation URLs

**Comment by agstephens** [comment]
Closing, as we have resolved elsewhere. I'm about to create some new issues.
